// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI7RIEuzXbjMc_vFy2EYIcc_bMujSgdNU',
    appId: '1:517068112470:web:1bb7bba1ec5ed5402b71f7',
    messagingSenderId: '517068112470',
    projectId: 'hair-salon-appointments',
    authDomain: 'hair-salon-appointments.firebaseapp.com',
    storageBucket: 'hair-salon-appointments.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-PTmzBa5rAOVUIXSkibDzrzp-IgglOg4',
    appId: '1:517068112470:android:1430331a27fda64b2b71f7',
    messagingSenderId: '517068112470',
    projectId: 'hair-salon-appointments',
    storageBucket: 'hair-salon-appointments.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP24JA_xay2a3mqVc4-JKQEWEceUFyZ1k',
    appId: '1:517068112470:ios:d0ed089052a4bf0b2b71f7',
    messagingSenderId: '517068112470',
    projectId: 'hair-salon-appointments',
    storageBucket: 'hair-salon-appointments.firebasestorage.app',
    iosBundleId: 'com.example.hairSalonApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP24JA_xay2a3mqVc4-JKQEWEceUFyZ1k',
    appId: '1:517068112470:ios:d0ed089052a4bf0b2b71f7',
    messagingSenderId: '517068112470',
    projectId: 'hair-salon-appointments',
    storageBucket: 'hair-salon-appointments.firebasestorage.app',
    iosBundleId: 'com.example.hairSalonApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBI7RIEuzXbjMc_vFy2EYIcc_bMujSgdNU',
    appId: '1:517068112470:web:88e94e2cbc081b1d2b71f7',
    messagingSenderId: '517068112470',
    projectId: 'hair-salon-appointments',
    authDomain: 'hair-salon-appointments.firebaseapp.com',
    storageBucket: 'hair-salon-appointments.firebasestorage.app',
  );
}
